version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "PR: Ignore For Release"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
